name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  AWS_REGION: "ap-south-1"  # Change to reflect your Region

# Permission can be added at job level or workflow level
permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read   # This is required for actions/checkout

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::288761748973:role/GitHubAction-AssumeRoleWithAction  # change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Put files to S3 bucket
        run: |
          aws s3 cp ./sample.txt s3://krupakaryasa
      - name: EKS GetCluster
        run: |
          ## check connectivity test
          aws eks list-clusters
          aws eks describe-cluster --name eks-demo --region ap-south-1
          aws update-kubeconfig --name eks-demo --region ap-south-1
          sleep 10
          
